---
version: 2.1

orbs:
  kitchen: sous-chefs/kitchen@2

workflows:
  kitchen:
    jobs:
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      # - kitchen/delivery:
      #     name: delivery
